include: [".well-known"]
theme: "just-the-docs"
baseurl: "/homepage" # the subpath of your site, e.g. /blog
url: "https://yangxqiao.github.io" # the base hostname & protocol for your site, e.g. http://example.com
